version: '3.8'

services:
  app:
    restart: on-failure  # Reinicia solo si el contenedor falla
    build: .             # Construye la imagen localmente desde el Dockerfile en este directorio
    image: backendcaffenet  # Nombre de la imagen local construida
    ports:
      - "8090:8082"      # Puerto mapeado (8090 en el host, 8082 en el contenedor)
    networks:
      - backendnet  # Conexión con la red, si decides usarla

volumes:
  mysql-data:

networks:
  backendnet:
    driver: bridge
