version: '3.8'

services:
  # Backend
  app:
    build: .               # Construye la imagen localmente desde el Dockerfile
    image: backend-caffenet # Nombre de la imagen
    ports:
      - "8090:8082"         # Mapeo de puertos
    depends_on:
      - mysql-db            # Asegura que MySQL se inicie primero
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-db:3306/CaffeNet  # Conexi칩n a MySQL
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: abcd1234
    networks:
      - backendnet

  # Base de datos MySQL
  mysql-db:
    image: mysql:8                # Imagen oficial de MySQL
    environment:
      MYSQL_ROOT_PASSWORD: abcd1234  # Contrase침a de root
      MYSQL_DATABASE: CaffeNet       # Base de datos a crear
    ports:
      - "3008:3306"                 # Exposici칩n de puertos
    volumes:
      - mysql-data:/var/lib/mysql   # Volumen persistente
    networks:
      - backendnet

  # Jenkins (solo para CI/CD)
  jenkins:
    image: jenkins/jenkins:lts     # Imagen oficial de Jenkins
    ports:
      - "8080:8080"                # Puerto para la UI de Jenkins
      - "50000:50000"              # Puerto para comunicaci칩n de nodos
    volumes:
      - jenkins-data:/var/jenkins_home # Volumen persistente para Jenkins
    networks:
      - backendnet

volumes:
  mysql-data:                      # Volumen persistente para MySQL
  jenkins-data:                    # Volumen persistente para Jenkins

networks:
  backendnet:
    driver: bridge
