services:
  app:
    build: .           # Construye la imagen localmente desde el Dockerfile en este directorio
    image: backendcaffenet        # Nombre de la imagen local construida
    ports:
      - "8090:8080"     # Puerto mapeado (8090 en el host, 8080 en el contenedor)
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/mydb
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: password

  db:
    image: postgres:14
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
