version: '3.8'

services:
  app:
    build: .                 # Construye la imagen desde tu Dockerfile en el backend
    image: backendcaffenet   # Nombre local de la imagen
    container_name: backend-app
    ports:
      - "8090:8082"          # Mapea el puerto externo 8090 al puerto interno del backend
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3308/CaffeNet
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: abcd1234
    networks:
      - backendnet

  db:
    image: mysql:8
    container_name: mysql-db
    environment:
      MYSQL_DATABASE: CaffeNet
      MYSQL_USER: root
      MYSQL_PASSWORD: abcd1234
      MYSQL_ROOT_PASSWORD: abcd1234
    ports:
      - "3308:3306"           # MySQL accesible desde localhost:3308
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - backendnet

volumes:
  mysql_data:

networks:
  backendnet:
