# docker-compose.yml corregido
version: '3.8'
services:
  app:
    image: miapp
# O alternativamente, si necesitas construir la imagen desde aquí:
# build: ./demo
    ports:
      - "8090:8080"  # Cambiado a 8090 para evitar conflicto con Jenkins
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/mydb
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: password
db:
  image: postgres:14
  environment:
    POSTGRES_DB: mydb
    POSTGRES_USER: user
    POSTGRES_PASSWORD: password
  ports:
    - "5432:5432"
  volumes:
    - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data: