version: '3.8'

services:
  app:
    build: .                     # Construye la imagen desde tu Dockerfile en el backend
    image: backendcaffenet       # Nombre local de la imagen
    container_name: backend-app
    ports:
      - "8090:8082"              # Mapea el puerto externo 8090 al puerto interno del backend
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-db:3308/CaffeNet  # Hostname del contenedor de la DB
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: abcd1234
    networks:
      - backendnet               # Misma red que la base de datos

networks:
  backendnet:
    driver: bridge
